[directory]
style = "bold bright-cyan"
truncation_length = 3
truncate_to_repo = true

[character]
success_symbol = "[â¯](bold bright-white)"
error_symbol = "[â¯](bold red)"

[git_branch]
style = "bold bright-magenta"

[git_status]
style = "bold bright-white"

[git_state]
style = "bold bright-white"

[nodejs]
format = "[$symbol($version )]($style)"
style = "bold bright-green"
symbol = "â¬¢ "

[php]
format = "[$symbol($version )]($style)"
style = "bold bright-blue"
symbol = "ğŸ˜ "

[python]
format = "[$symbol$pyenv_prefix($version )]($style)"
style = "bold bright-yellow"
symbol = "ğŸ "
